"use client";
import { useEffect,useMemo,useState } from "react";
type Product={id:number;sku:string;barcode?:string;name:string;price:string|number};
type Item={product_id:number;name:string;warehouse_id:number;quantity:number;unit_price:number};
export default function SaleClient(){
 const[products,setProducts]=useState<Product[]>([]),[customers,setCustomers]=useState<any[]>([]),[warehouses,setWarehouses]=useState<any[]>([]);
 const[rows,setRows]=useState<any[]>([]),[cart,setCart]=useState<Item[]>([]),[search,setSearch]=useState(""),[err,setErr]=useState("");
 const[warehouse,setWarehouse]=useState(""),[customer,setCustomer]=useState(""),[method,setMethod]=useState("CASH"),[discount,setDiscount]=useState("0");
 const[installments,setInstallments]=useState("1"),[firstDue,setFirstDue]=useState(""),[deliveryAddress,setDeliveryAddress]=useState("");
 async function load(){const[s,c,w]=await Promise.all([fetch("/api/sales"),fetch("/api/customers"),fetch("/api/warehouses")]);setRows(await s.json());setCustomers(await c.json());setWarehouses(await w.json())}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const t=setTimeout(()=>{fetch("/api/products?q="+encodeURIComponent(search)).then(r=>r.json()).then(setProducts)},180);return()=>clearTimeout(t)},[search]);
 const subtotal=useMemo(()=>cart.reduce((a,i)=>a+i.quantity*i.unit_price,0),[cart]);
 const total=Math.max(0,subtotal-Number(discount||0));
 function add(p:Product){if(!warehouse){setErr("Selecione o depósito antes de adicionar produtos.");return}
   setCart(v=>{const found=v.find(i=>i.product_id===p.id&&i.warehouse_id===Number(warehouse));return found?v.map(i=>i===found?{...i,quantity:i.quantity+1}:i):[...v,{product_id:p.id,name:p.name,warehouse_id:Number(warehouse),quantity:1,unit_price:Number(p.price)}]});setSearch("")}
 async function finish(){setErr("");const body:any={customer_id:customer?Number(customer):null,payment_method:method,discount:Number(discount||0),items:cart};if(method==="CREDIT"){body.installments=Number(installments||1);body.first_due_date=firstDue||undefined}if(deliveryAddress)body.delivery={address:deliveryAddress};const r=await fetch("/api/sales",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setErr((await r.json()).error);return}setCart([]);setDiscount("0");setDeliveryAddress("");load()}
 return <><h1>PDV / Vendas</h1><div className="card">
 <div className="form"><select className="input" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Cliente balcão</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>
 <select className="input" value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">Selecione o depósito</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select>
 <input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, SKU ou código de barras"/></div>
 {!!search&&<div>{products.slice(0,10).map(p=><button className="btn" style={{margin:"6px"}} key={p.id} onClick={()=>add(p)}>{p.sku} — {p.name} — R$ {p.price}</button>)}</div>}
 <table className="table"><thead><tr><th>Produto</th><th>Qtd.</th><th>Preço</th><th>Subtotal</th><th></th></tr></thead><tbody>{cart.map((i,n)=><tr key={n}><td>{i.name}</td><td><input className="input" type="number" min="0.001" step="0.001" value={i.quantity} onChange={e=>setCart(v=>v.map((x,j)=>j===n?{...x,quantity:Number(e.target.value)}:x))}/></td><td><input className="input" type="number" step="0.01" value={i.unit_price} onChange={e=>setCart(v=>v.map((x,j)=>j===n?{...x,unit_price:Number(e.target.value)}:x))}/></td><td>R$ {(i.quantity*i.unit_price).toFixed(2)}</td><td><button className="btn" onClick={()=>setCart(v=>v.filter((_,j)=>j!==n))}>Remover</button></td></tr>)}</tbody></table>
 <div className="form" style={{marginTop:12}}><select className="input" value={method} onChange={e=>setMethod(e.target.value)}><option value="CASH">Dinheiro</option><option value="PIX">PIX</option><option value="CARD">Cartão</option><option value="CREDIT">Crediário</option></select><input className="input" type="number" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)} placeholder="Desconto"/><input className="input" value={deliveryAddress} onChange={e=>setDeliveryAddress(e.target.value)} placeholder="Endereço de entrega (opcional)"/>{method==="CREDIT"&&<><input className="input" type="number" min="1" max="24" value={installments} onChange={e=>setInstallments(e.target.value)} placeholder="Parcelas"/><input className="input" type="date" value={firstDue} onChange={e=>setFirstDue(e.target.value)}/></>}</div>
 <p><b>Subtotal: R$ {subtotal.toFixed(2)} | Total: R$ {total.toFixed(2)}</b></p><button className="btn" disabled={!cart.length} onClick={finish}>Finalizar venda</button>{err&&<p>{err}</p>}</div><br/>
 <div className="card"><table className="table"><thead><tr><th>ID</th><th>Cliente</th><th>Pagamento</th><th>Total</th><th>Vendedor</th><th>Data</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.customer||"Balcão"}</td><td>{r.payment_method}</td><td>{r.total}</td><td>{r.seller}</td><td>{String(r.created_at)}</td></tr>)}</tbody></table></div></>
}